/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#002045',
        'primary-container': '#1a365d',
        'on-primary': '#ffffff',
        'on-primary-container': '#86a0cd',
        secondary: '#3d57b6',
        'secondary-container': '#829bfe',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#082d8d',
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-variant': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#43474e',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#74777f',
        'outline-variant': '#c4c6cf',
        'surface-tint': '#455f88',
        'inverse-primary': '#adc7f7',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#adc7f7',
        'on-primary-fixed': '#001b3c',
        'on-primary-fixed-variant': '#2d476f',
        tertiary: '#1d2123',
        'tertiary-container': '#333638',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#9c9fa1',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
      },
      fontFamily: {
        sans: ['DM Sans', 'sans-serif'],
        dmsans: ['DM Sans', 'sans-serif'],
        newsreader: ['Newsreader', 'serif'],
      },
      maxWidth: {
        container: '1100px',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
